eureka:
    client:
        enabled: true
        initial-instance-info-replication-interval-seconds: 120
        instance-info-replication-interval-seconds: 120
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka
            registerWithEureka: true
    instance:
        prefer-ip-address: true
feign:
    circuitbreaker:
        enabled: true
    client:
        config:
            default:
                loggerLevel: basic
            soldier-service:
                connectTimeout: 1000
                loggerLevel: basic
                readTimeout: 2000
info:
    app:
        description: '@project.description@'
        encoding: '@project.build.sourceEncoding@'
        java:
            version: '@java.version@'
        name: '@project.name@'
        version: '@project.version@'
logging:
    level:
        org:
            hibernate:
                SQL: INFO
                type:
                    descriptor:
                        sql:
                            BasicBinder: INFO
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
emp:
    army:
        troop:
            fields-to-escape:
        description: '@project.description@'
        dob:
            format: dd-MM-yyyy
        version: '@project.version@'
        soldier:
            service:
                port: 8083
                url: 127.0.0.1:${emp.army.soldier.service.port}
server:
    port: 17001
spring:
    cloud:
        discovery:
            enabled: true
        loadbalancer:
            ribbon:
                enabled: false
        service-registry:
            auto-registration:
                enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ArMy
        url: jdbc:mysql://127.0.0.1:3306/emp_army_db
        username: emp_army_manager
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: UTC
                show_sql: true
                use_sql_comments: true
    sleuth:
        sampler:
            percentage: 1.0
        web:
            skipPattern: (^cleanup.*|.+favicon.*)
    zipkin:
        baseUrl: http://127.0.0.1:9411
        enabled: true
    swagger-ui:
        enabled: true
